# Pipeline testing — capture as many overtakes as possible

This notebook replaces the earlier failed draft and tries to recover **as many genuine overtakes as possible** from FastF1 race data.

## Main fixes vs the previous attempt

- use **`EventName`** instead of `Country` to load sessions, so races like **Miami / Las Vegas / Emilia Romagna** are not lost,
- include **all actual race weekends** (`RoundNumber > 0`) instead of dropping sprint weekends,
- keep a **per-race audit table** so missing races are visible,
- extract **raw pairwise order flips between consecutive laps** as the widest lap-level approximation,
- then tune filters to get closer to published season totals.

## Important limitation

This is still a **lap-end** approximation. It can miss:

- overtakes and repasses inside the same lap,
- passes only visible in higher-frequency timing,
- some classification artifacts around pits / retirements / safety cars.

So this notebook is meant as a **better counting experiment**, not a perfect official overtake counter.

In [1]:
import warnings
from itertools import combinations, product
from pathlib import Path
import sys

import fastf1
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

warnings.filterwarnings("ignore", category=FutureWarning)

ROOT = Path("..").resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pipeline import fastf1_utils as ffu

CACHE_DIR = ROOT / "cache"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
fastf1.Cache.enable_cache(str(CACHE_DIR))

REFERENCE_TOTALS = {
    2022: 785,
    2023: 858,
    2024: 788,
    # 2025: add a published season total here when you want error columns for that year
}

DEFAULT_YEARS = [2022, 2023, 2024, 2025]

print("Cache:", CACHE_DIR)
print("Reference totals:", REFERENCE_TOTALS)

Cache: /Users/aminnami/Desktop/hamid/ai_in_industry/formula1-overtake-prediction/cache
Reference totals: {2022: 785, 2023: 858, 2024: 788}

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Extraction strategy

For each race:

1. Load the **Race** session using the schedule row's **`EventName`**.
2. Build a lap-level table of driver positions.
3. For each pair of drivers present on consecutive laps, mark a **raw flip event** when their relative order reverses from lap `L` to lap `L+1`.
4. Store rich metadata for later filtering:
   - pit involvement,
   - safety car / yellow flags,
   - position jump size,
   - whether the pair was adjacent before or after the pass,
   - timing accuracy.
5. Compare filtered totals with published season references.

This raw-flip approach intentionally aims wide: it will catch more possible overtakes than the existing battle detector, then let us trim obvious artifacts afterward.

In [2]:
def race_event_rows(year: int) -> pd.DataFrame:
    schedule = fastf1.get_event_schedule(year)
    out = schedule.copy()
    out = out[out["RoundNumber"].fillna(0).astype(int) > 0].copy()
    return out.reset_index(drop=True)


def load_race_session(year: int, event_name: str):
    return ffu.load_session(year=year, gp=event_name, identifier="R", cache_path=str(CACHE_DIR))


def session_year(session, fallback_year: int) -> int:
    try:
        val = session.event.get("Year")
        if val is not None and not pd.isna(val):
            return int(val)
    except Exception:
        pass
    try:
        dt = session.event.get("EventDate")
        if dt is not None and not pd.isna(dt):
            return int(pd.Timestamp(dt).year)
    except Exception:
        pass
    return int(fallback_year)


def lap_frame(session) -> pd.DataFrame:
    cols = [
        "Driver",
        "LapNumber",
        "Position",
        "LapTime",
        "PitInTime",
        "PitOutTime",
        "LapStartTime",
        "Time",
        "TrackStatus",
        "IsAccurate",
    ]
    present = [c for c in cols if c in session.laps.columns]
    df = session.laps[present].copy()
    df = df[df["Driver"].notna() & df["LapNumber"].notna() & df["Position"].notna()].copy()
    df["Driver"] = df["Driver"].astype(str)
    df["LapNumber"] = df["LapNumber"].astype(int)
    df["Position"] = df["Position"].astype(int)
    if "IsAccurate" in df.columns:
        df["IsAccurate"] = df["IsAccurate"].fillna(False).astype(bool)
    else:
        df["IsAccurate"] = True
    return df.sort_values(["LapNumber", "Position", "Driver"]).reset_index(drop=True)


def pit_related(row: pd.Series) -> bool:
    return pd.notna(row.get("PitInTime")) or pd.notna(row.get("PitOutTime"))


def extract_raw_overtake_candidates(session, fallback_year: int) -> pd.DataFrame:
    laps = lap_frame(session)
    if laps.empty:
        return pd.DataFrame()

    year = session_year(session, fallback_year)
    race_name = str(session.event.get("EventName") or "Unknown")
    round_number = int(session.event.get("RoundNumber") or 0)
    event_format = str(session.event.get("EventFormat") or "")
    max_lap = int(laps["LapNumber"].max())

    rows: list[dict] = []
    for lap in range(1, max_lap):
        cur = laps[laps["LapNumber"] == lap].set_index("Driver", drop=False)
        nxt = laps[laps["LapNumber"] == lap + 1].set_index("Driver", drop=False)
        shared = sorted(set(cur.index) & set(nxt.index))
        if len(shared) < 2:
            continue

        safety_car, yellow_flag = ffu.detect_safety_car_and_flags(session, lap + 1)

        for i, a in enumerate(shared):
            for b in shared[i + 1 :]:
                a0, b0 = cur.loc[a], cur.loc[b]
                a1, b1 = nxt.loc[a], nxt.loc[b]
                pa0, pb0 = int(a0["Position"]), int(b0["Position"])
                pa1, pb1 = int(a1["Position"]), int(b1["Position"])

                if pa0 == pb0 or pa1 == pb1:
                    continue
                if (pa0 - pb0) * (pa1 - pb1) >= 0:
                    continue

                if pa0 > pb0 and pa1 < pb1:
                    overtaker, overtaken = a, b
                    ov0, ov1, od0, od1 = a0, a1, b0, b1
                    overtaker_prev, overtaker_next = pa0, pa1
                    overtaken_prev, overtaken_next = pb0, pb1
                elif pb0 > pa0 and pb1 < pa1:
                    overtaker, overtaken = b, a
                    ov0, ov1, od0, od1 = b0, b1, a0, a1
                    overtaker_prev, overtaker_next = pb0, pb1
                    overtaken_prev, overtaken_next = pa0, pa1
                else:
                    continue

                rows.append(
                    {
                        "year": year,
                        "race_name": race_name,
                        "round_number": round_number,
                        "event_format": event_format,
                        "lap_number": lap + 1,
                        "overtaker": overtaker,
                        "overtaken": overtaken,
                        "overtaker_prev_pos": overtaker_prev,
                        "overtaker_next_pos": overtaker_next,
                        "overtaken_prev_pos": overtaken_prev,
                        "overtaken_next_pos": overtaken_next,
                        "position_gain": int(overtaker_prev - overtaker_next),
                        "consecutive_before": bool(overtaker_prev == overtaken_prev + 1),
                        "consecutive_after": bool(overtaken_next == overtaker_next + 1),
                        "pit_related": bool(
                            pit_related(ov0) or pit_related(ov1) or pit_related(od0) or pit_related(od1)
                        ),
                        "accurate_timing": bool(
                            ov0.get("IsAccurate", True)
                            and ov1.get("IsAccurate", True)
                            and od0.get("IsAccurate", True)
                            and od1.get("IsAccurate", True)
                        ),
                        "safety_car": bool(safety_car),
                        "yellow_flag": bool(yellow_flag),
                        "lap1_or_restart_like": bool(lap + 1 <= 2),
                    }
                )

    out = pd.DataFrame(rows)
    if out.empty:
        return out
    return out.sort_values(["year", "round_number", "lap_number", "overtaker", "overtaken"]).reset_index(drop=True)

In [3]:
_SESSION_CACHE: dict[tuple[int, str], object] = {}
_RAW_CACHE: dict[tuple[int, str], pd.DataFrame] = {}


def get_or_load_session(year: int, event_name: str):
    key = (year, event_name)
    if key not in _SESSION_CACHE:
        _SESSION_CACHE[key] = load_race_session(year, event_name)
    return _SESSION_CACHE[key]


def collect_season_raw_events(year: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    frames: list[pd.DataFrame] = []
    audit_rows: list[dict] = []

    events = race_event_rows(year)
    for _, event in tqdm(events.iterrows(), total=len(events), desc=f"Season {year}"):
        event_name = str(event["EventName"])
        event_format = str(event.get("EventFormat") or "")
        try:
            key = (year, event_name)
            if key in _RAW_CACHE:
                raw = _RAW_CACHE[key].copy()
            else:
                session = get_or_load_session(year, event_name)
                raw = extract_raw_overtake_candidates(session, year)
                _RAW_CACHE[key] = raw.copy()

            audit_rows.append(
                {
                    "year": year,
                    "round_number": int(event.get("RoundNumber") or 0),
                    "event_name": event_name,
                    "event_format": event_format,
                    "status": "ok",
                    "raw_events": int(len(raw)),
                    "error": None,
                }
            )
            if not raw.empty:
                frames.append(raw)
        except Exception as exc:
            audit_rows.append(
                {
                    "year": year,
                    "round_number": int(event.get("RoundNumber") or 0),
                    "event_name": event_name,
                    "event_format": event_format,
                    "status": "error",
                    "raw_events": 0,
                    "error": str(exc),
                }
            )

    raw_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    audit_df = pd.DataFrame(audit_rows).sort_values(["round_number", "event_name"]).reset_index(drop=True)
    return raw_df, audit_df


def season_audit_summary(audit_df: pd.DataFrame) -> pd.DataFrame:
    if audit_df.empty:
        return audit_df.copy()
    return pd.DataFrame(
        {
            "expected_races": [int(len(audit_df))],
            "loaded_ok": [int((audit_df["status"] == "ok").sum())],
            "failed": [int((audit_df["status"] == "error").sum())],
            "races_with_zero_events": [int(((audit_df["status"] == "ok") & (audit_df["raw_events"] == 0)).sum())],
            "total_raw_events": [int(audit_df["raw_events"].sum())],
        }
    )

In [4]:
def apply_filters(
    df: pd.DataFrame,
    *,
    exclude_pit_related: bool = True,
    exclude_lap1: bool = True,
    exclude_safety_car: bool = True,
    exclude_yellow_flag: bool = False,
    require_accurate_timing: bool = False,
    adjacency_rule: str = "none",  # none / before / after / either
    max_position_gain: int | None = None,
) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    out = df.copy()
    if exclude_pit_related:
        out = out[~out["pit_related"]]
    if exclude_lap1:
        out = out[~out["lap1_or_restart_like"]]
    if exclude_safety_car:
        out = out[~out["safety_car"]]
    if exclude_yellow_flag:
        out = out[~out["yellow_flag"]]
    if require_accurate_timing:
        out = out[out["accurate_timing"]]
    if adjacency_rule == "before":
        out = out[out["consecutive_before"]]
    elif adjacency_rule == "after":
        out = out[out["consecutive_after"]]
    elif adjacency_rule == "either":
        out = out[out["consecutive_before"] | out["consecutive_after"]]
    if max_position_gain is not None:
        out = out[out["position_gain"] <= max_position_gain]
    return out.reset_index(drop=True)


def compare_to_reference(season_raw: dict[int, pd.DataFrame], **filter_kwargs) -> pd.DataFrame:
    rows = []
    for year, raw in season_raw.items():
        filtered = apply_filters(raw, **filter_kwargs)
        ref = REFERENCE_TOTALS.get(year)
        observed = int(len(filtered))
        rows.append(
            {
                "year": year,
                "raw_candidates": int(len(raw)),
                "filtered_events": observed,
                "reference_total": ref,
                "signed_error": None if ref is None else observed - int(ref),
                "abs_error": None if ref is None else abs(observed - int(ref)),
            }
        )
    return pd.DataFrame(rows).sort_values("year").reset_index(drop=True)


def filter_grid_search(season_raw: dict[int, pd.DataFrame]) -> pd.DataFrame:
    rows = []
    for exclude_pit_related, exclude_lap1, exclude_safety_car, adjacency_rule, max_position_gain in product(
        [True, False],
        [True, False],
        [True, False],
        ["none", "before", "after", "either"],
        [1, 2, 3, None],
    ):
        comp = compare_to_reference(
            season_raw,
            exclude_pit_related=exclude_pit_related,
            exclude_lap1=exclude_lap1,
            exclude_safety_car=exclude_safety_car,
            exclude_yellow_flag=False,
            require_accurate_timing=False,
            adjacency_rule=adjacency_rule,
            max_position_gain=max_position_gain,
        )
        known = comp[comp["reference_total"].notna()].copy()
        rows.append(
            {
                "exclude_pit_related": exclude_pit_related,
                "exclude_lap1": exclude_lap1,
                "exclude_safety_car": exclude_safety_car,
                "adjacency_rule": adjacency_rule,
                "max_position_gain": max_position_gain,
                "total_abs_error": int(known["abs_error"].sum()),
            }
        )
    return pd.DataFrame(rows).sort_values("total_abs_error").reset_index(drop=True)

In [5]:
YEARS = DEFAULT_YEARS

season_raw: dict[int, pd.DataFrame] = {}
season_audit: dict[int, pd.DataFrame] = {}

for year in YEARS:
    raw_df, audit_df = collect_season_raw_events(year)
    season_raw[year] = raw_df
    season_audit[year] = audit_df

    print(f"\n=== {year} ===")
    display(season_audit_summary(audit_df))
    display(audit_df[["round_number", "event_name", "event_format", "status", "raw_events", "error"]])
    print(f"Raw candidate events: {len(raw_df):,}")
    if not raw_df.empty:
        print(f"Races with raw events: {raw_df['race_name'].nunique()}")
        display(raw_df.head(20))

Season 2022:   0%|          | 0/22 [00:00<?, ?it/s]

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']

Season 2022:   5%|▍         | 1/22 [00:02<00:56,  2.67s/it]

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	No lap data for driver 22

core        WARNING 	No lap data for driver 47

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 47)

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '31', '4', '10', '20', '44', '24', '27', '18', '23', '77', '14', '3', '6', '22', '47']

Season 2022:   9%|▉         | 2/22 [00:04<00:45,  2.27s/it]

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 16 completed the race distance 00:00.140000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['16', '11', '63', '44', '4', '3', '31', '77', '10', '23', '24', '18', '47', '20', '22', '6', '14', '1', '5', '55']

Season 2022:  14%|█▎        | 3/22 [00:07<00:44,  2.33s/it]

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '63', '77', '16', '22', '5', '20', '18', '23', '10', '44', '31', '24', '6', '47', '3', '14', '55']

Season 2022:  18%|█▊        | 4/22 [00:09<00:42,  2.38s/it]

core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '44', '77', '31', '23', '18', '14', '22', '3', '6', '47', '20', '5', '10', '4', '24']

Season 2022:  23%|██▎       | 5/22 [00:11<00:41,  2.41s/it]

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '55', '44', '77', '31', '4', '14', '22', '5', '3', '10', '47', '18', '6', '20', '23', '24', '16']

Season 2022:  27%|██▋       | 6/22 [00:14<00:40,  2.52s/it]

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '11'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '44'

core        WARNING 	Fixed incorrect tyre stint information for driver '77'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '3'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

core        WARNING 	Fixed incorrect tyre stint information for driver '24'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '47'

core        WARNING 	Fixed incorrect tyre stint information for driver '20'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['11', '55', '1', '16', '63', '4', '14', '44', '77', '5', '10', '31', '3', '18', '6', '24', '22', '23', '47', '20']

Season 2022:  32%|███▏      | 7/22 [00:17<00:40,  2.68s/it]

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '44', '10', '5', '14', '3', '4', '31', '77', '23', '22', '47', '6', '18', '20', '24', '16', '55']

Season 2022:  36%|███▋      | 8/22 [00:19<00:35,  2.51s/it]

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '55', '44', '63', '16', '31', '77', '24', '14', '18', '3', '5', '23', '10', '4', '6', '20', '22', '47', '11']

Season 2022:  41%|████      | 9/22 [00:22<00:33,  2.58s/it]

core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['55', '11', '44', '16', '14', '4', '1', '47', '5', '20', '18', '6', '3', '22', '31', '10', '77', '63', '24', '23']

Season 2022:  45%|████▌     | 10/22 [00:24<00:29,  2.43s/it]

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '44'

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '47'

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

core        WARNING 	Fixed incorrect tyre stint information for driver '20'

core        WARNING 	Fixed incorrect tyre stint information for driver '3'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '77'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '24'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

core        WARNING 	Fixed incorrect tyre stint information for driver '11'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 16 completed the race distance 00:00.024000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '44', '63', '31', '47', '4', '20', '3', '14', '77', '23', '18', '24', '10', '22', '5', '55', '6', '11']

Season 2022:  50%|█████     | 11/22 [00:27<00:27,  2.53s/it]

core           INFO 	Loading data for French Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:00.041000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '14', '4', '31', '3', '18', '5', '10', '23', '77', '47', '24', '6', '20', '16', '22']

Season 2022:  55%|█████▍    | 12/22 [00:29<00:24,  2.43s/it]

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '55', '11', '16', '4', '14', '31', '5', '18', '10', '24', '47', '3', '20', '23', '6', '22', '77']

Season 2022:  59%|█████▉    | 13/22 [00:32<00:23,  2.61s/it]

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '63', '14', '16', '31', '5', '10', '23', '18', '4', '22', '24', '3', '20', '47', '6', '77', '44']

Season 2022:  64%|██████▎   | 14/22 [00:34<00:19,  2.42s/it]

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '16', '44', '11', '14', '4', '55', '31', '18', '10', '23', '47', '5', '20', '24', '3', '6', '77', '22']

Season 2022:  68%|██████▊   | 15/22 [00:37<00:18,  2.62s/it]

core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '44', '11', '4', '10', '45', '24', '31', '47', '77', '22', '6', '20', '3', '18', '14', '5']

Season 2022:  73%|███████▎  | 16/22 [00:39<00:15,  2.51s/it]

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '4', '3', '18', '1', '5', '44', '10', '77', '20', '47', '63', '22', '31', '23', '14', '6', '24']

Season 2022:  77%|███████▋  | 17/22 [00:42<00:12,  2.54s/it]

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '31', '44', '5', '14', '63', '6', '4', '3', '18', '22', '20', '77', '24', '47', '10', '55', '23']

Season 2022:  82%|████████▏ | 18/22 [00:44<00:09,  2.35s/it]

events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'

core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '11', '63', '4', '14', '5', '20', '22', '31', '24', '23', '10', '47', '3', '6', '18', '77', '55']

Season 2022:  86%|████████▋ | 19/22 [00:46<00:06,  2.33s/it]

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '11', '63', '55', '16', '3', '31', '4', '77', '10', '23', '24', '5', '18', '47', '20', '6', '14', '22']

Season 2022:  91%|█████████ | 20/22 [00:49<00:05,  2.52s/it]

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '14', '1', '11', '31', '77', '18', '5', '24', '47', '10', '23', '6', '22', '4', '20', '3']

Season 2022:  95%|█████████▌| 21/22 [00:52<00:02,  2.57s/it]

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '55', '63', '4', '31', '18', '3', '5', '22', '24', '23', '10', '77', '47', '20', '44', '6', '14']

Season 2022: 100%|██████████| 22/22 [00:54<00:00,  2.54s/it]

Season 2022: 100%|██████████| 22/22 [00:54<00:00,  2.50s/it]

=== 2022 ===

   expected_races  loaded_ok  failed  races_with_zero_events  total_raw_events
0              22         22       0                       0              3580

,round_number,event_name,event_format,status,raw_events,error
0,1,Bahrain Grand Prix,conventional,ok,257,None
1,2,Saudi Arabian Grand Prix,conventional,ok,94,None
2,3,Australian Grand Prix,conventional,ok,132,None
3,4,Emilia Romagna Grand Prix,sprint,ok,74,None
4,5,Miami Grand Prix,conventional,ok,153,None
5,6,Spanish Grand Prix,conventional,ok,193,None
6,7,Monaco Grand Prix,conventional,ok,80,None
7,8,Azerbaijan Grand Prix,conventional,ok,107,None
8,9,Canadian Grand Prix,conventional,ok,114,None
9,10,British Grand Prix,conventional,ok,148,None
10,11,Austrian Grand Prix,sprint,ok,262,None
11,12,French Grand Prix,conventional,ok,100,None
12,13,Hungarian Grand Prix,conventional,ok,241,None
13,14,Belgian Grand Prix,conventional,ok,238,None
14,15,Dutch Grand Prix,conventional,ok,181,None
15,16,Italian Grand Prix,conventional,ok,166,None
16,17,Singapore Grand Prix,conventional,ok,64,None
17,18,Japanese Grand Prix,conventional,ok,139,None
18,19,United States Grand Prix,conventional,ok,244,None
19,20,Mexico City Grand Prix,conventional,ok,109,None
20,21,São Paulo Grand Prix,sprint,ok,287,None
21,22,Abu Dhabi Grand Prix,conventional,ok,197,None

Raw candidate events: 3,580
Races with raw events: 22

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2022,Bahrain Grand Prix,1,conventional,2,STR,NOR,17,16,16,17,1,True,True,False,False,False,False,True
1,2022,Bahrain Grand Prix,1,conventional,2,ZHO,LAT,19,18,18,19,1,True,True,False,False,False,False,True
2,2022,Bahrain Grand Prix,1,conventional,3,PER,MAG,6,5,5,6,1,True,True,False,True,False,False,False
3,2022,Bahrain Grand Prix,1,conventional,3,ZHO,NOR,18,17,17,18,1,True,True,False,True,False,False,False
4,2022,Bahrain Grand Prix,1,conventional,4,ZHO,STR,17,16,16,17,1,True,True,False,True,False,False,False
5,2022,Bahrain Grand Prix,1,conventional,5,RUS,MAG,7,6,6,7,1,True,True,False,True,False,False,False
6,2022,Bahrain Grand Prix,1,conventional,5,TSU,ALB,12,11,11,12,1,True,True,False,True,False,False,False
7,2022,Bahrain Grand Prix,1,conventional,5,ZHO,HUL,16,15,15,16,1,True,True,False,True,False,False,False
8,2022,Bahrain Grand Prix,1,conventional,6,BOT,MSC,14,13,13,14,1,True,True,False,True,False,False,False
9,2022,Bahrain Grand Prix,1,conventional,6,RIC,LAT,20,19,19,20,1,True,True,False,True,False,False,False
10,2022,Bahrain Grand Prix,1,conventional,7,LAT,RIC,20,19,19,20,1,True,True,False,True,False,False,False
11,2022,Bahrain Grand Prix,1,conventional,7,ZHO,MSC,15,14,14,15,1,True,True,False,True,False,False,False
12,2022,Bahrain Grand Prix,1,conventional,8,BOT,ALB,13,12,12,13,1,True,True,False,True,False,False,False
13,2022,Bahrain Grand Prix,1,conventional,8,OCO,ALO,10,9,9,10,1,True,True,False,True,False,False,False
14,2022,Bahrain Grand Prix,1,conventional,9,STR,HUL,17,16,16,17,1,True,True,False,True,False,False,False
15,2022,Bahrain Grand Prix,1,conventional,10,PER,HAM,5,4,4,5,1,True,True,False,True,False,False,False
16,2022,Bahrain Grand Prix,1,conventional,10,STR,MSC,16,15,15,16,1,True,True,False,True,False,False,False
17,2022,Bahrain Grand Prix,1,conventional,10,ZHO,ALB,14,13,13,14,1,True,True,False,True,False,False,False
18,2022,Bahrain Grand Prix,1,conventional,11,TSU,ALO,11,10,10,11,1,True,True,True,False,False,False,False
19,2022,Bahrain Grand Prix,1,conventional,12,ALB,ALO,14,13,11,20,1,False,False,True,False,False,False,False

Season 2023:   0%|          | 0/22 [00:00<?, ?it/s]

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

Season 2023:   5%|▍         | 1/22 [00:02<00:50,  2.38s/it]

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 11 completed the race distance 00:00.035000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']

Season 2023:   9%|▉         | 2/22 [00:04<00:45,  2.28s/it]

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']

Season 2023:  14%|█▎        | 3/22 [00:07<00:45,  2.38s/it]

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']

Season 2023:  18%|█▊        | 4/22 [00:09<00:42,  2.34s/it]

core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']

Season 2023:  23%|██▎       | 5/22 [00:11<00:41,  2.43s/it]

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']

Season 2023:  27%|██▋       | 6/22 [00:15<00:43,  2.71s/it]

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:00.037000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']

Season 2023:  32%|███▏      | 7/22 [00:18<00:41,  2.78s/it]

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']

Season 2023:  36%|███▋      | 8/22 [00:20<00:39,  2.79s/it]

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '4', '14', '55', '63', '44', '18', '10', '23', '24', '2', '31', '77', '81', '21', '20', '22', '27']

Season 2023:  41%|████      | 9/22 [00:23<00:36,  2.84s/it]

core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']

Season 2023:  45%|████▌     | 10/22 [00:26<00:31,  2.66s/it]

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']

Season 2023:  50%|█████     | 11/22 [00:28<00:29,  2.64s/it]

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '44', '14', '63', '4', '31', '18', '22', '10', '77', '24', '23', '20', '3', '2', '27', '55', '81']

Season 2023:  55%|█████▍    | 12/22 [00:30<00:24,  2.44s/it]

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:02.059000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']

Season 2023:  59%|█████▉    | 13/22 [00:33<00:23,  2.63s/it]

core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 06:25.888000 before the recorded end of the session.

core        WARNING 	Driver 11 completed the race distance 06:19.824000 before the recorded end of the session.

core        WARNING 	Driver 55 completed the race distance 06:14.695000 before the recorded end of the session.

core        WARNING 	Driver 16 completed the race distance 06:14.511000 before the recorded end of the session.

core        WARNING 	Driver 63 completed the race distance 06:07.860000 before the recorded end of the session.

core        WARNING 	Driver 44 completed the race distance 05:48.209000 before the recorded end of the session.

core        WARNING 	Driver 23 completed the race distance 05:40.782000 before the recorded end of the session.

core        WARNING 	Driver 4 completed the race distance 05:40.439000 before the recorded end of the session.

core        WARNING 	Driver 14 completed the race distance 05:39.594000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']

Season 2023:  64%|██████▎   | 14/22 [00:36<00:20,  2.53s/it]

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	No lap data for driver 18

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']

Season 2023:  68%|██████▊   | 15/22 [00:38<00:17,  2.50s/it]

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:00.076000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']

Season 2023:  73%|███████▎  | 16/22 [00:40<00:14,  2.35s/it]

events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	No lap data for driver 55

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '16', '14', '31', '77', '24', '11', '18', '10', '23', '20', '22', '27', '40', '2', '44', '55']

Season 2023:  77%|███████▋  | 17/22 [00:42<00:11,  2.34s/it]

events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'

core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']

Season 2023:  82%|████████▏ | 18/22 [00:45<00:09,  2.32s/it]

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']

Season 2023:  86%|████████▋ | 19/22 [00:47<00:07,  2.49s/it]

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '14', '11', '18', '55', '10', '44', '22', '31', '2', '27', '3', '81', '63', '77', '24', '20', '23', '16']

Season 2023:  91%|█████████ | 20/22 [00:50<00:04,  2.44s/it]

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:00.001000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']

Season 2023:  95%|█████████▌| 21/22 [00:52<00:02,  2.35s/it]

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']

Season 2023: 100%|██████████| 22/22 [00:55<00:00,  2.45s/it]

Season 2023: 100%|██████████| 22/22 [00:55<00:00,  2.51s/it]

=== 2023 ===

   expected_races  loaded_ok  failed  races_with_zero_events  total_raw_events
0              22         22       0                       0              4158

,round_number,event_name,event_format,status,raw_events,error
0,1,Bahrain Grand Prix,conventional,ok,189,None
1,2,Saudi Arabian Grand Prix,conventional,ok,116,None
2,3,Australian Grand Prix,conventional,ok,86,None
3,4,Azerbaijan Grand Prix,sprint_shootout,ok,99,None
4,5,Miami Grand Prix,conventional,ok,155,None
5,6,Monaco Grand Prix,conventional,ok,102,None
6,7,Spanish Grand Prix,conventional,ok,283,None
7,8,Canadian Grand Prix,conventional,ok,122,None
8,9,Austrian Grand Prix,sprint_shootout,ok,189,None
9,10,British Grand Prix,conventional,ok,107,None
10,11,Hungarian Grand Prix,conventional,ok,166,None
11,12,Belgian Grand Prix,sprint_shootout,ok,224,None
12,13,Dutch Grand Prix,conventional,ok,366,None
13,14,Italian Grand Prix,conventional,ok,165,None
14,15,Singapore Grand Prix,conventional,ok,118,None
15,16,Japanese Grand Prix,conventional,ok,192,None
16,17,Qatar Grand Prix,sprint_shootout,ok,403,None
17,18,United States Grand Prix,sprint_shootout,ok,224,None
18,19,Mexico City Grand Prix,conventional,ok,168,None
19,20,São Paulo Grand Prix,sprint_shootout,ok,144,None
20,21,Las Vegas Grand Prix,conventional,ok,236,None
21,22,Abu Dhabi Grand Prix,conventional,ok,304,None

Raw candidate events: 4,158
Races with raw events: 22

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2023,Bahrain Grand Prix,1,conventional,2,GAS,MAG,19,18,18,19,1,True,True,False,False,False,False,True
1,2023,Bahrain Grand Prix,1,conventional,3,DEV,MAG,20,19,19,20,1,True,True,False,True,False,False,False
2,2023,Bahrain Grand Prix,1,conventional,4,ALB,NOR,12,11,10,12,1,False,True,False,True,False,False,False
3,2023,Bahrain Grand Prix,1,conventional,4,OCO,NOR,11,10,10,12,1,True,False,False,True,False,False,False
4,2023,Bahrain Grand Prix,1,conventional,4,TSU,HUL,15,14,14,15,1,True,True,False,True,False,False,False
5,2023,Bahrain Grand Prix,1,conventional,5,STR,BOT,9,8,8,9,1,True,True,False,True,False,False,False
6,2023,Bahrain Grand Prix,1,conventional,9,DEV,GAS,19,18,18,19,1,True,True,True,False,False,False,False
7,2023,Bahrain Grand Prix,1,conventional,10,MAG,GAS,20,19,19,20,1,True,True,True,False,False,False,False
8,2023,Bahrain Grand Prix,1,conventional,10,SAR,NOR,13,12,12,13,1,True,True,True,False,False,False,False
9,2023,Bahrain Grand Prix,1,conventional,11,DEV,NOR,18,17,13,20,1,False,False,True,False,False,False,False
10,2023,Bahrain Grand Prix,1,conventional,11,DEV,TSU,18,17,14,18,1,False,True,True,False,False,False,False
11,2023,Bahrain Grand Prix,1,conventional,11,GAS,NOR,20,19,13,20,1,False,True,True,False,False,False,False
12,2023,Bahrain Grand Prix,1,conventional,11,HUL,NOR,15,16,13,20,-1,False,False,True,False,False,False,False
13,2023,Bahrain Grand Prix,1,conventional,11,HUL,TSU,15,16,14,18,-1,True,False,True,False,False,False,False
14,2023,Bahrain Grand Prix,1,conventional,11,MAG,DEV,19,15,18,17,4,True,False,True,False,False,False,False
15,2023,Bahrain Grand Prix,1,conventional,11,MAG,HUL,19,15,15,16,4,False,True,True,False,False,False,False
16,2023,Bahrain Grand Prix,1,conventional,11,MAG,NOR,19,15,13,20,4,False,False,True,False,False,False,False
17,2023,Bahrain Grand Prix,1,conventional,11,MAG,TSU,19,15,14,18,4,False,False,True,False,False,False,False
18,2023,Bahrain Grand Prix,1,conventional,11,PIA,HUL,16,13,15,16,3,True,False,True,False,False,False,False
19,2023,Bahrain Grand Prix,1,conventional,11,PIA,NOR,16,13,13,20,3,False,False,True,False,False,False,False

Season 2024:   0%|          | 0/24 [00:00<?, ?it/s]

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

Season 2024:   4%|▍         | 1/24 [00:02<01:00,  2.64s/it]

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']

Season 2024:   8%|▊         | 2/24 [00:04<00:50,  2.30s/it]

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']

Season 2024:  12%|█▎        | 3/24 [00:06<00:47,  2.25s/it]

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']

Season 2024:  17%|█▋        | 4/24 [00:09<00:44,  2.20s/it]

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']

Season 2024:  21%|██        | 5/24 [00:11<00:43,  2.28s/it]

core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']

Season 2024:  25%|██▌       | 6/24 [00:14<00:42,  2.38s/it]

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']

Season 2024:  29%|██▉       | 7/24 [00:16<00:42,  2.49s/it]

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']

Season 2024:  33%|███▎      | 8/24 [00:19<00:40,  2.53s/it]

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']

Season 2024:  38%|███▊      | 9/24 [00:21<00:38,  2.56s/it]

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']

Season 2024:  42%|████▏     | 10/24 [00:24<00:37,  2.67s/it]

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']

Season 2024:  46%|████▌     | 11/24 [00:27<00:36,  2.78s/it]

core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']

Season 2024:  50%|█████     | 12/24 [00:30<00:31,  2.63s/it]

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']

Season 2024:  54%|█████▍    | 13/24 [00:33<00:29,  2.70s/it]

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '3'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']

Season 2024:  58%|█████▊    | 14/24 [00:35<00:25,  2.51s/it]

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']

Season 2024:  62%|██████▎   | 15/24 [00:38<00:24,  2.75s/it]

core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

Season 2024:  67%|██████▋   | 16/24 [00:40<00:21,  2.67s/it]

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']

Season 2024:  71%|███████   | 17/24 [00:43<00:19,  2.72s/it]

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']

Season 2024:  75%|███████▌  | 18/24 [00:46<00:16,  2.78s/it]

events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'

core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '4', '81', '63', '11', '27', '30', '43', '20', '10', '14', '22', '18', '23', '77', '31', '24', '44']

Season 2024:  79%|███████▉  | 19/24 [00:49<00:13,  2.75s/it]

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']

Season 2024:  83%|████████▎ | 20/24 [00:52<00:11,  2.87s/it]

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	No lap data for driver 23

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '31', '10', '63', '16', '4', '22', '81', '30', '44', '11', '50', '77', '14', '24', '55', '43', '23', '18', '27']

Season 2024:  88%|████████▊ | 21/24 [00:55<00:08,  2.90s/it]

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Driver 63: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 55: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 16: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver  1: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver  4: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 81: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 30: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver 77: Lap timing integrity check failed for 2 lap(s)

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']

Season 2024:  92%|█████████▏| 22/24 [00:57<00:05,  2.75s/it]

events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '43'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']

Season 2024:  96%|█████████▌| 23/24 [01:00<00:02,  2.71s/it]

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

Season 2024: 100%|██████████| 24/24 [01:03<00:00,  2.71s/it]

Season 2024: 100%|██████████| 24/24 [01:03<00:00,  2.63s/it]

=== 2024 ===

   expected_races  loaded_ok  failed  races_with_zero_events  total_raw_events
0              24         24       0                       0              3785

,round_number,event_name,event_format,status,raw_events,error
0,1,Bahrain Grand Prix,conventional,ok,217,None
1,2,Saudi Arabian Grand Prix,conventional,ok,63,None
2,3,Australian Grand Prix,conventional,ok,159,None
3,4,Japanese Grand Prix,conventional,ok,179,None
4,5,Chinese Grand Prix,sprint_qualifying,ok,221,None
5,6,Miami Grand Prix,sprint_qualifying,ok,131,None
6,7,Emilia Romagna Grand Prix,conventional,ok,135,None
7,8,Monaco Grand Prix,conventional,ok,15,None
8,9,Canadian Grand Prix,conventional,ok,139,None
9,10,Spanish Grand Prix,conventional,ok,246,None
10,11,Austrian Grand Prix,sprint_qualifying,ok,217,None
11,12,British Grand Prix,conventional,ok,84,None
12,13,Hungarian Grand Prix,conventional,ok,232,None
13,14,Belgian Grand Prix,conventional,ok,205,None
14,15,Dutch Grand Prix,conventional,ok,160,None
15,16,Italian Grand Prix,conventional,ok,191,None
16,17,Azerbaijan Grand Prix,conventional,ok,117,None
17,18,Singapore Grand Prix,conventional,ok,131,None
18,19,United States Grand Prix,sprint_qualifying,ok,148,None
19,20,Mexico City Grand Prix,conventional,ok,137,None
20,21,São Paulo Grand Prix,sprint_qualifying,ok,107,None
21,22,Las Vegas Grand Prix,conventional,ok,307,None
22,23,Qatar Grand Prix,sprint_qualifying,ok,104,None
23,24,Abu Dhabi Grand Prix,conventional,ok,140,None

Raw candidate events: 3,785
Races with raw events: 24

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2024,Bahrain Grand Prix,1,conventional,2,SAR,RIC,15,14,14,15,1,True,True,False,False,False,False,True
1,2024,Bahrain Grand Prix,1,conventional,3,NOR,ALO,7,6,6,7,1,True,True,False,True,False,False,False
2,2024,Bahrain Grand Prix,1,conventional,3,RUS,LEC,3,2,2,3,1,True,True,False,True,False,False,False
3,2024,Bahrain Grand Prix,1,conventional,5,PIA,ALO,8,7,7,8,1,True,True,False,True,False,False,False
4,2024,Bahrain Grand Prix,1,conventional,5,STR,BOT,19,18,18,19,1,True,True,False,True,False,False,False
5,2024,Bahrain Grand Prix,1,conventional,7,PER,LEC,4,3,3,4,1,True,True,False,True,False,False,False
6,2024,Bahrain Grand Prix,1,conventional,9,BOT,STR,19,18,18,19,1,True,True,True,False,False,False,False
7,2024,Bahrain Grand Prix,1,conventional,9,OCO,ZHO,16,15,13,16,1,False,True,True,False,False,False,False
8,2024,Bahrain Grand Prix,1,conventional,9,RIC,ZHO,15,14,13,16,1,False,False,True,False,False,False,False
9,2024,Bahrain Grand Prix,1,conventional,9,SAR,ZHO,14,13,13,16,1,True,False,True,False,False,False,False
10,2024,Bahrain Grand Prix,1,conventional,10,BOT,OCO,18,15,15,16,3,False,True,True,False,False,False,False
11,2024,Bahrain Grand Prix,1,conventional,10,BOT,SAR,18,15,13,20,3,False,False,True,False,False,False,False
12,2024,Bahrain Grand Prix,1,conventional,10,BOT,ZHO,18,15,16,17,3,False,False,True,False,False,False,False
13,2024,Bahrain Grand Prix,1,conventional,10,GAS,OCO,17,14,15,16,3,False,False,True,False,False,False,False
14,2024,Bahrain Grand Prix,1,conventional,10,GAS,SAR,17,14,13,20,3,False,False,True,False,False,False,False
15,2024,Bahrain Grand Prix,1,conventional,10,GAS,ZHO,17,14,16,17,3,True,False,True,False,False,False,False
16,2024,Bahrain Grand Prix,1,conventional,10,HAM,ALO,9,8,8,9,1,True,True,False,True,False,False,False
17,2024,Bahrain Grand Prix,1,conventional,10,HUL,SAR,20,19,13,20,1,False,True,True,False,False,False,False
18,2024,Bahrain Grand Prix,1,conventional,10,OCO,SAR,15,16,13,20,-1,False,False,True,False,False,False,False
19,2024,Bahrain Grand Prix,1,conventional,10,RIC,SAR,14,13,13,20,1,True,False,True,False,False,False,False

Season 2025:   0%|          | 0/24 [00:00<?, ?it/s]

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '87'

core        WARNING 	Fixed incorrect tyre stint information for driver '30'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

Season 2025:   4%|▍         | 1/24 [00:02<00:49,  2.17s/it]

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

Season 2025:   8%|▊         | 2/24 [00:04<00:53,  2.43s/it]

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']

Season 2025:  12%|█▎        | 3/24 [00:07<00:53,  2.57s/it]

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']

Season 2025:  17%|█▋        | 4/24 [00:10<00:54,  2.70s/it]

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']

Season 2025:  21%|██        | 5/24 [00:12<00:49,  2.58s/it]

core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']

Season 2025:  25%|██▌       | 6/24 [00:15<00:45,  2.54s/it]

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']

Season 2025:  29%|██▉       | 7/24 [00:18<00:45,  2.70s/it]

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']

Season 2025:  33%|███▎      | 8/24 [00:21<00:45,  2.85s/it]

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

Season 2025:  38%|███▊      | 9/24 [00:24<00:44,  2.95s/it]

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']

Season 2025:  42%|████▏     | 10/24 [00:27<00:42,  3.02s/it]

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']

Season 2025:  46%|████▌     | 11/24 [00:30<00:37,  2.89s/it]

core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

Season 2025:  50%|█████     | 12/24 [00:32<00:32,  2.70s/it]

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '81'

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '44'

core        WARNING 	Fixed incorrect tyre stint information for driver '30'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '87'

core        WARNING 	Fixed incorrect tyre stint information for driver '27'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '12'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

core        WARNING 	Fixed incorrect tyre stint information for driver '43'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '16', '1', '63', '23', '44', '30', '5', '10', '87', '27', '22', '18', '31', '12', '14', '55', '43', '6']

Season 2025:  54%|█████▍    | 13/24 [00:35<00:30,  2.80s/it]

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '14', '5', '18', '30', '1', '12', '6', '44', '27', '55', '23', '31', '22', '43', '10', '87']

Season 2025:  58%|█████▊    | 14/24 [00:39<00:30,  3.07s/it]

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['81', '1', '6', '63', '23', '87', '18', '14', '22', '31', '43', '30', '55', '27', '5', '12', '10', '4', '16', '44']

Season 2025:  62%|██████▎   | 15/24 [00:42<00:28,  3.19s/it]

core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']

Season 2025:  67%|██████▋   | 16/24 [00:45<00:23,  2.98s/it]

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '55', '12', '30', '22', '4', '44', '16', '6', '5', '87', '23', '31', '14', '27', '18', '10', '43', '81']

Season 2025:  71%|███████   | 17/24 [00:48<00:20,  2.93s/it]

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']

Season 2025:  75%|███████▌  | 18/24 [00:51<00:17,  3.00s/it]

events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'

core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '44', '81', '63', '22', '27', '87', '14', '30', '18', '12', '23', '31', '6', '43', '5', '10', '55']

Season 2025:  79%|███████▉  | 19/24 [00:54<00:14,  2.93s/it]

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '1', '87', '81', '12', '63', '44', '31', '5', '22', '23', '6', '18', '10', '43', '55', '14', '27', '30']

Season 2025:  83%|████████▎ | 20/24 [00:56<00:11,  2.89s/it]

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core        WARNING 	Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.

core           INFO 	Finished loading data for 20 drivers: ['4', '12', '1', '63', '81', '87', '30', '6', '27', '10', '23', '31', '55', '14', '43', '18', '22', '44', '16', '5']

Season 2025:  88%|████████▊ | 21/24 [00:59<00:08,  2.85s/it]

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']

Season 2025:  92%|█████████▏| 22/24 [01:02<00:05,  2.74s/it]

events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '55', '4', '12', '63', '14', '16', '30', '22', '23', '44', '5', '43', '31', '10', '18', '6', '87', '27']

Season 2025:  96%|█████████▌| 23/24 [01:04<00:02,  2.70s/it]

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

Season 2025: 100%|██████████| 24/24 [01:07<00:00,  2.73s/it]

Season 2025: 100%|██████████| 24/24 [01:07<00:00,  2.81s/it]

=== 2025 ===

   expected_races  loaded_ok  failed  races_with_zero_events  total_raw_events
0              24         24       0                       0              3906

,round_number,event_name,event_format,status,raw_events,error
0,1,Australian Grand Prix,conventional,ok,94,None
1,2,Chinese Grand Prix,sprint_qualifying,ok,174,None
2,3,Japanese Grand Prix,conventional,ok,125,None
3,4,Bahrain Grand Prix,conventional,ok,302,None
4,5,Saudi Arabian Grand Prix,conventional,ok,110,None
5,6,Miami Grand Prix,sprint_qualifying,ok,78,None
6,7,Emilia Romagna Grand Prix,conventional,ok,188,None
7,8,Monaco Grand Prix,conventional,ok,81,None
8,9,Spanish Grand Prix,conventional,ok,211,None
9,10,Canadian Grand Prix,conventional,ok,199,None
10,11,Austrian Grand Prix,conventional,ok,180,None
11,12,British Grand Prix,conventional,ok,216,None
12,13,Belgian Grand Prix,sprint_qualifying,ok,120,None
13,14,Hungarian Grand Prix,conventional,ok,186,None
14,15,Dutch Grand Prix,conventional,ok,147,None
15,16,Italian Grand Prix,conventional,ok,149,None
16,17,Azerbaijan Grand Prix,conventional,ok,107,None
17,18,Singapore Grand Prix,conventional,ok,158,None
18,19,United States Grand Prix,sprint_qualifying,ok,132,None
19,20,Mexico City Grand Prix,conventional,ok,174,None
20,21,São Paulo Grand Prix,sprint_qualifying,ok,299,None
21,22,Las Vegas Grand Prix,conventional,ok,108,None
22,23,Qatar Grand Prix,sprint_qualifying,ok,126,None
23,24,Abu Dhabi Grand Prix,conventional,ok,242,None

Raw candidate events: 3,906
Races with raw events: 24

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2025,Australian Grand Prix,1,conventional,14,ANT,HUL,13,12,12,13,1,True,True,False,True,False,False,False
1,2025,Australian Grand Prix,1,conventional,16,HUL,ANT,13,12,12,13,1,True,True,False,True,False,False,False
2,2025,Australian Grand Prix,1,conventional,17,ANT,HUL,13,12,12,13,1,True,True,False,True,False,False,False
3,2025,Australian Grand Prix,1,conventional,17,PIA,VER,3,2,2,3,1,True,True,False,True,False,False,False
4,2025,Australian Grand Prix,1,conventional,19,LAW,OCO,16,15,15,16,1,True,True,False,True,False,False,False
5,2025,Australian Grand Prix,1,conventional,22,ANT,STR,12,11,11,12,1,True,True,False,True,False,False,False
6,2025,Australian Grand Prix,1,conventional,33,OCO,LAW,16,14,15,15,2,True,True,True,False,False,False,False
7,2025,Australian Grand Prix,1,conventional,34,BEA,LAW,16,15,15,16,1,True,True,True,False,False,False,False
8,2025,Australian Grand Prix,1,conventional,39,LAW,BEA,16,14,15,16,2,True,False,True,False,False,False,False
9,2025,Australian Grand Prix,1,conventional,39,LAW,OCO,16,14,14,15,2,False,True,True,False,False,False,False
10,2025,Australian Grand Prix,1,conventional,43,TSU,LEC,6,5,5,6,1,True,True,False,True,False,False,False
11,2025,Australian Grand Prix,1,conventional,44,ALB,PIA,7,9,2,15,-2,False,False,True,False,False,False,False
12,2025,Australian Grand Prix,1,conventional,44,ANT,PIA,10,11,2,15,-1,False,False,True,False,False,False,False
13,2025,Australian Grand Prix,1,conventional,44,BOR,PIA,13,13,2,15,0,False,False,True,False,False,False,False
14,2025,Australian Grand Prix,1,conventional,44,GAS,ALB,9,4,7,9,5,False,False,True,False,False,False,False
15,2025,Australian Grand Prix,1,conventional,44,GAS,LEC,9,4,6,5,5,False,True,False,True,False,False,False
16,2025,Australian Grand Prix,1,conventional,44,GAS,NOR,9,4,1,6,5,False,False,True,False,False,False,False
17,2025,Australian Grand Prix,1,conventional,44,GAS,PIA,9,4,2,15,5,False,False,True,False,False,False,False
18,2025,Australian Grand Prix,1,conventional,44,GAS,RUS,9,4,4,8,5,False,False,True,False,False,False,False
19,2025,Australian Grand Prix,1,conventional,44,HAM,ALB,8,3,7,9,5,True,False,True,False,False,False,False

In [6]:
grid = filter_grid_search(season_raw)
display(grid.head(20))

best = grid.iloc[0].to_dict()
best_filters = {
    "exclude_pit_related": bool(best["exclude_pit_related"]),
    "exclude_lap1": bool(best["exclude_lap1"]),
    "exclude_safety_car": bool(best["exclude_safety_car"]),
    "exclude_yellow_flag": False,
    "require_accurate_timing": False,
    "adjacency_rule": str(best["adjacency_rule"]),
    "max_position_gain": None if pd.isna(best["max_position_gain"]) else int(best["max_position_gain"]),
}

comparison = compare_to_reference(season_raw, **best_filters)
print("Chosen filters:", best_filters)
display(comparison)

for year in YEARS:
    sample = apply_filters(season_raw[year], **best_filters)
    print(f"\nSample filtered events for {year}: {len(sample):,}")
    display(sample.head(20))

,exclude_pit_related,exclude_lap1,exclude_safety_car,adjacency_rule,max_position_gain,total_abs_error
0,True,False,False,none,NaN,53
1,True,False,True,none,NaN,53
2,True,False,False,none,3.0,58
3,True,False,True,none,3.0,58
4,True,True,True,none,NaN,119
5,True,True,False,none,NaN,119
6,True,False,False,none,2.0,120
7,True,False,True,none,2.0,120
8,True,True,True,none,3.0,130
9,True,True,False,none,3.0,130
10,True,False,True,either,NaN,174
11,True,False,False,either,NaN,174
12,True,False,True,either,3.0,179
13,True,False,False,either,3.0,179
14,True,True,True,none,2.0,197
15,True,True,False,none,2.0,197
16,True,False,True,either,2.0,242
17,True,False,False,either,2.0,242
18,True,True,True,either,NaN,250
19,True,True,False,either,NaN,250

Chosen filters: {'exclude_pit_related': True, 'exclude_lap1': False, 'exclude_safety_car': False, 'exclude_yellow_flag': False, 'require_accurate_timing': False, 'adjacency_rule': 'none', 'max_position_gain': None}

,year,raw_candidates,filtered_events,reference_total,signed_error,abs_error
0,2022,3580,794,785.0,9.0,9.0
1,2023,4158,834,858.0,-24.0,24.0
2,2024,3785,768,788.0,-20.0,20.0
3,2025,3906,746,NaN,NaN,NaN

Sample filtered events for 2022: 794

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2022,Bahrain Grand Prix,1,conventional,2,STR,NOR,17,16,16,17,1,True,True,False,False,False,False,True
1,2022,Bahrain Grand Prix,1,conventional,2,ZHO,LAT,19,18,18,19,1,True,True,False,False,False,False,True
2,2022,Bahrain Grand Prix,1,conventional,3,PER,MAG,6,5,5,6,1,True,True,False,True,False,False,False
3,2022,Bahrain Grand Prix,1,conventional,3,ZHO,NOR,18,17,17,18,1,True,True,False,True,False,False,False
4,2022,Bahrain Grand Prix,1,conventional,4,ZHO,STR,17,16,16,17,1,True,True,False,True,False,False,False
5,2022,Bahrain Grand Prix,1,conventional,5,RUS,MAG,7,6,6,7,1,True,True,False,True,False,False,False
6,2022,Bahrain Grand Prix,1,conventional,5,TSU,ALB,12,11,11,12,1,True,True,False,True,False,False,False
7,2022,Bahrain Grand Prix,1,conventional,5,ZHO,HUL,16,15,15,16,1,True,True,False,True,False,False,False
8,2022,Bahrain Grand Prix,1,conventional,6,BOT,MSC,14,13,13,14,1,True,True,False,True,False,False,False
9,2022,Bahrain Grand Prix,1,conventional,6,RIC,LAT,20,19,19,20,1,True,True,False,True,False,False,False
10,2022,Bahrain Grand Prix,1,conventional,7,LAT,RIC,20,19,19,20,1,True,True,False,True,False,False,False
11,2022,Bahrain Grand Prix,1,conventional,7,ZHO,MSC,15,14,14,15,1,True,True,False,True,False,False,False
12,2022,Bahrain Grand Prix,1,conventional,8,BOT,ALB,13,12,12,13,1,True,True,False,True,False,False,False
13,2022,Bahrain Grand Prix,1,conventional,8,OCO,ALO,10,9,9,10,1,True,True,False,True,False,False,False
14,2022,Bahrain Grand Prix,1,conventional,9,STR,HUL,17,16,16,17,1,True,True,False,True,False,False,False
15,2022,Bahrain Grand Prix,1,conventional,10,PER,HAM,5,4,4,5,1,True,True,False,True,False,False,False
16,2022,Bahrain Grand Prix,1,conventional,10,STR,MSC,16,15,15,16,1,True,True,False,True,False,False,False
17,2022,Bahrain Grand Prix,1,conventional,10,ZHO,ALB,14,13,13,14,1,True,True,False,True,False,False,False
18,2022,Bahrain Grand Prix,1,conventional,12,RIC,LAT,20,18,19,19,2,True,True,False,True,False,False,False
19,2022,Bahrain Grand Prix,1,conventional,14,ALO,HUL,17,14,15,15,3,False,True,False,True,False,False,False

Sample filtered events for 2023: 834

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2023,Bahrain Grand Prix,1,conventional,2,GAS,MAG,19,18,18,19,1,True,True,False,False,False,False,True
1,2023,Bahrain Grand Prix,1,conventional,3,DEV,MAG,20,19,19,20,1,True,True,False,True,False,False,False
2,2023,Bahrain Grand Prix,1,conventional,4,ALB,NOR,12,11,10,12,1,False,True,False,True,False,False,False
3,2023,Bahrain Grand Prix,1,conventional,4,OCO,NOR,11,10,10,12,1,True,False,False,True,False,False,False
4,2023,Bahrain Grand Prix,1,conventional,4,TSU,HUL,15,14,14,15,1,True,True,False,True,False,False,False
5,2023,Bahrain Grand Prix,1,conventional,5,STR,BOT,9,8,8,9,1,True,True,False,True,False,False,False
6,2023,Bahrain Grand Prix,1,conventional,14,BOT,MAG,10,8,9,9,2,True,True,False,True,False,False,False
7,2023,Bahrain Grand Prix,1,conventional,17,ALO,BOT,7,6,6,7,1,True,True,False,True,False,False,False
8,2023,Bahrain Grand Prix,1,conventional,18,RUS,BOT,8,7,7,8,1,True,True,False,True,False,False,False
9,2023,Bahrain Grand Prix,1,conventional,18,ZHO,HUL,17,15,16,16,2,True,True,False,True,False,False,False
10,2023,Bahrain Grand Prix,1,conventional,20,STR,BOT,9,8,8,9,1,True,True,False,True,False,False,False
11,2023,Bahrain Grand Prix,1,conventional,23,NOR,OCO,19,18,18,19,1,True,True,False,True,False,False,False
12,2023,Bahrain Grand Prix,1,conventional,25,ZHO,DEV,15,14,14,15,1,True,True,False,True,False,False,False
13,2023,Bahrain Grand Prix,1,conventional,26,PER,LEC,3,2,2,3,1,True,True,False,True,False,False,False
14,2023,Bahrain Grand Prix,1,conventional,38,ALO,HAM,6,5,5,6,1,True,True,False,True,False,False,False
15,2023,Bahrain Grand Prix,1,conventional,43,ZHO,DEV,13,12,12,13,1,True,True,False,True,False,False,False
16,2023,Bahrain Grand Prix,1,conventional,44,SAR,DEV,14,13,13,14,1,True,True,False,True,False,False,False
17,2023,Bahrain Grand Prix,1,conventional,45,ALO,SAI,4,3,3,4,1,True,True,False,True,False,False,False
18,2023,Bahrain Grand Prix,1,conventional,47,SAR,ZHO,13,12,12,13,1,True,True,False,True,False,False,False
19,2023,Bahrain Grand Prix,1,conventional,51,MAG,DEV,15,14,14,15,1,True,True,False,True,False,False,False

Sample filtered events for 2024: 768

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2024,Bahrain Grand Prix,1,conventional,2,SAR,RIC,15,14,14,15,1,True,True,False,False,False,False,True
1,2024,Bahrain Grand Prix,1,conventional,3,NOR,ALO,7,6,6,7,1,True,True,False,True,False,False,False
2,2024,Bahrain Grand Prix,1,conventional,3,RUS,LEC,3,2,2,3,1,True,True,False,True,False,False,False
3,2024,Bahrain Grand Prix,1,conventional,5,PIA,ALO,8,7,7,8,1,True,True,False,True,False,False,False
4,2024,Bahrain Grand Prix,1,conventional,5,STR,BOT,19,18,18,19,1,True,True,False,True,False,False,False
5,2024,Bahrain Grand Prix,1,conventional,7,PER,LEC,4,3,3,4,1,True,True,False,True,False,False,False
6,2024,Bahrain Grand Prix,1,conventional,10,HAM,ALO,9,8,8,9,1,True,True,False,True,False,False,False
7,2024,Bahrain Grand Prix,1,conventional,17,SAI,LEC,5,4,4,5,1,True,True,False,True,False,False,False
8,2024,Bahrain Grand Prix,1,conventional,17,TSU,STR,12,11,11,12,1,True,True,False,True,False,False,False
9,2024,Bahrain Grand Prix,1,conventional,18,SAI,RUS,4,3,3,4,1,True,True,False,True,False,False,False
10,2024,Bahrain Grand Prix,1,conventional,21,RIC,OCO,16,15,15,16,1,True,True,False,True,False,False,False
11,2024,Bahrain Grand Prix,1,conventional,33,STR,ZHO,15,13,14,14,2,True,True,False,True,False,False,False
12,2024,Bahrain Grand Prix,1,conventional,34,RUS,ALO,9,6,8,7,3,True,True,False,True,False,False,False
13,2024,Bahrain Grand Prix,1,conventional,36,NOR,ALO,7,6,5,7,1,False,True,False,True,False,False,False
14,2024,Bahrain Grand Prix,1,conventional,38,MAG,HUL,13,12,12,14,1,True,False,False,True,False,False,False
15,2024,Bahrain Grand Prix,1,conventional,38,TSU,HUL,14,13,12,14,1,False,True,False,True,False,False,False
16,2024,Bahrain Grand Prix,1,conventional,39,HAM,ALO,8,7,7,8,1,True,True,False,True,False,False,False
17,2024,Bahrain Grand Prix,1,conventional,40,PIA,ALO,9,8,8,9,1,True,True,False,True,False,False,False
18,2024,Bahrain Grand Prix,1,conventional,44,ALO,ZHO,11,10,10,11,1,True,True,False,True,False,False,False
19,2024,Bahrain Grand Prix,1,conventional,46,LEC,RUS,5,4,4,5,1,True,True,False,True,False,False,False

Sample filtered events for 2025: 746

,year,race_name,round_number,event_format,lap_number,overtaker,overtaken,overtaker_prev_pos,overtaker_next_pos,overtaken_prev_pos,overtaken_next_pos,position_gain,consecutive_before,consecutive_after,pit_related,accurate_timing,safety_car,yellow_flag,lap1_or_restart_like
0,2025,Australian Grand Prix,1,conventional,14,ANT,HUL,13,12,12,13,1,True,True,False,True,False,False,False
1,2025,Australian Grand Prix,1,conventional,16,HUL,ANT,13,12,12,13,1,True,True,False,True,False,False,False
2,2025,Australian Grand Prix,1,conventional,17,ANT,HUL,13,12,12,13,1,True,True,False,True,False,False,False
3,2025,Australian Grand Prix,1,conventional,17,PIA,VER,3,2,2,3,1,True,True,False,True,False,False,False
4,2025,Australian Grand Prix,1,conventional,19,LAW,OCO,16,15,15,16,1,True,True,False,True,False,False,False
5,2025,Australian Grand Prix,1,conventional,22,ANT,STR,12,11,11,12,1,True,True,False,True,False,False,False
6,2025,Australian Grand Prix,1,conventional,43,TSU,LEC,6,5,5,6,1,True,True,False,True,False,False,False
7,2025,Australian Grand Prix,1,conventional,44,GAS,LEC,9,4,6,5,5,False,True,False,True,False,False,False
8,2025,Australian Grand Prix,1,conventional,44,HAM,LEC,8,3,6,5,5,False,False,False,True,False,False,False
9,2025,Australian Grand Prix,1,conventional,45,HAM,TSU,3,2,2,3,1,True,True,False,True,False,False,False
10,2025,Australian Grand Prix,1,conventional,46,LEC,TSU,5,2,3,4,3,False,False,False,True,False,False,False
11,2025,Australian Grand Prix,1,conventional,51,PIA,OCO,13,12,12,13,1,True,True,False,False,False,False,False
12,2025,Australian Grand Prix,1,conventional,52,LEC,HAM,10,9,9,10,1,True,True,False,False,False,False,False
13,2025,Australian Grand Prix,1,conventional,53,PIA,TSU,12,11,11,12,1,True,True,False,True,False,False,False
14,2025,Australian Grand Prix,1,conventional,54,HAM,GAS,10,9,8,10,1,False,True,False,True,False,False,False
15,2025,Australian Grand Prix,1,conventional,54,LEC,GAS,9,8,8,10,1,True,False,False,True,False,False,False
16,2025,Australian Grand Prix,1,conventional,55,PIA,GAS,11,10,10,11,1,True,True,False,True,False,False,False
17,2025,Australian Grand Prix,1,conventional,56,ANT,ALB,5,4,4,5,1,True,True,False,True,False,False,False
18,2025,Australian Grand Prix,1,conventional,57,PIA,HAM,10,9,9,10,1,True,True,False,True,False,False,False
19,2025,Chinese Grand Prix,2,sprint_qualifying,16,HAM,BEA,9,7,8,9,2,True,False,False,True,False,False,False

## How to read the output

- **Raw candidate events**: widest lap-level estimate of possible overtakes.
- **Audit table**: confirms whether every race loaded and whether any races still return zero events.
- **Grid search**: tries filter combinations to match reference totals as closely as possible.
- **Filtered events**: the current best approximation, not an official count.

If totals are still far off, the next step is to use **higher-frequency timing** than lap-end positions, because same-lap pass/repass sequences are invisible here.